############################################################
# +------------------------------------------------------+ #
# |                    Fundamentals                      | #
# +------------------------------------------------------+ #
############################################################

# Seconds before teleport
Teleport_Delay: 3
# Minutes until considered away from keyboard.
Afk_Delay: 3
# If enabled, color codes starting with '&' will convert automatically.
Sign_Colors: true
# If a location has been set for First Join (/setspawn fs) then make sure to have this set to true.
First_Join: true
Join_Message: '&e%p has joined the game!'
Quit_Message: '&e%p has left the game!'
Allow_Unsafe_Enchantments: false
Starter_Kit: 'None'
Scheduled_Shutdown_Message: 'Server will restart in %m minutes'
Allow_Metrics: true

############################################################
# +------------------------------------------------------+ #
# |                 FundamentalsSafety                   | #
# +------------------------------------------------------+ #
############################################################

Prevent_Fire_Damage: false
Prevent_Lava_Damage: false

############################################################
# +------------------------------------------------------+ #
# |                  FundamentalsKits                    | #
# +------------------------------------------------------+ #
############################################################

# delay is measured in seconds
# Spaces between words will be converted from "_"
# In the lore, you may use "%n" to express a new line.
# Colors are allowed as long as their code comes after a '&'
# Enchantments and their level should be separeted by a '%'

Kits:
    StarterKit:
        delay: 25
        items:
            - STONE_PICKAXE 1 0 Starter_Pickaxe &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_SPADE 1 0 Start_Spade &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_AXE 1 0 Starter_Axe &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_SWORD 1 0 Starter_Sword &eThis_item&f_is_received%nfrom_your_starter_kit. sharpness%1

############################################################
# +------------------------------------------------------+ #
# |                  FundamentalsHome                    | #
# +------------------------------------------------------+ #
############################################################

#
# Players are allowed to have the default amount of sethomes. If you wish for a player to be able to make more,
# make sure they have the appropriate permission.
# Example: Fundamentals.Homes.VIP by default gives the player 5 default sethomes.
#

Default_SetHomes: 1
Home_Permissions:
    - VIP 5

############################################################
# +------------------------------------------------------+ #
# |                 FundamentalsEconomy                  | #
# +------------------------------------------------------+ #
############################################################

# The starting balance new players have in their wallet.
Starting_Balance: 20
# When using '/money' or '/bal', what symbol should be used as a prefix to the shown balance?
Currency_Symbol: '$'
# What is the singular word when referring to your currency?
Currency_Singular: 'credit'
# What is the plural word when referring to your currency?
Currency_Plural: 'credits'
# What is the maximum amount of money a player can have? Do not put more than 10000000000000.
Max_Balance: 10000000000000
# What is the minimum amount of money a player can have? Player must have permission of
Min_Balance: -10000
# What is the minimal to be paid with '/pay' ?
Min_Pay_Amount: 0.01

############################################################
# +------------------------------------------------------+ #
# |                   FundamentalsChat                   | #
# +------------------------------------------------------+ #
############################################################

# Replace certain expressions with emojis.
Emoji_Chat: true
# Play a sound and text notification for a player when someone uses @TheirUsername.
Player_Mention: true