#Seconds before teleport
Teleport_Delay: 3
#Minutes until considered away from keyboard.
Afk_Delay: 3
#If enabled, color codes starting with '&' will convert automatically.
Sign_Colors: true
Join_Message: '&e&l%p has joined the game!'
Quit_Message: '&e&l%p has quit the game!'
Allow_Unsafe_Enchantments: false
Starter_Kit: 'None'
Scheduled_Shutdown_Message: 'Server will restart in %m minutes'
Allow_Metrics: true

#
# Kits
#

#delay is measured in seconds
#Spaces between words will be converted from "_"
#In the lore, you may use "%n" to express a new line.
#Colors are allowed as long as their code comes after a '&'
#Enchantments and their level should be separeted by a '%'

Kits:
    StarterKit:
        delay: 25
        items:
            - STONE_PICKAXE 1 0 Starter_Pickaxe &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_SPADE 1 0 Start_Spade &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_AXE 1 0 Starter_Axe &eThis_item&f_is_received%nfrom_your_starter_kit.
            - STONE_SWORD 1 0 Starter_Sword &eThis_item&f_is_received%nfrom_your_starter_kit. DAMAGE_ALL%1